# Generated by Django 4.0.1 on 2022-04-14 19:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date_post_length_post_tags_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='length',
            field=models.IntegerField(verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.JSONField(default=list, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
    ]
