# Generated by Django 4.0.1 on 2022-04-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posttranslation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttranslation',
            old_name='tags',
            new_name='role',
        ),
    ]
