# Generated by Django 4.0.1 on 2022-04-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_tags_posttranslation_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttranslation',
            old_name='text',
            new_name='overview',
        ),
    ]
