# Generated by Django 4.0.1 on 2022-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_text_posttranslation_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='image',
            field=models.ImageField(default='', upload_to='lectures'),
            preserve_default=False,
        ),
    ]
