# Generated by Django 4.0.1 on 2022-04-02 17:11

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_duration_project_goal_project_outcomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcomes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
