# Generated by Django 4.0.1 on 2022-04-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_date_alter_project_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(max_length=128),
        ),
    ]
