# Generated by Django 4.0.1 on 2022-04-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='what',
            new_name='why',
        ),
    ]
