# Generated by Django 4.0.1 on 2022-04-14 19:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_what_project_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(max_length=128, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=ckeditor.fields.RichTextField(verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcomes',
            field=models.JSONField(default=list, verbose_name='outcomes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=ckeditor.fields.RichTextField(verbose_name='overview'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.JSONField(default=list, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_title',
            field=ckeditor.fields.RichTextField(verbose_name='sub_title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='when',
            field=ckeditor.fields.RichTextField(verbose_name='when'),
        ),
        migrations.AlterField(
            model_name='project',
            name='where',
            field=ckeditor.fields.RichTextField(verbose_name='where'),
        ),
        migrations.AlterField(
            model_name='project',
            name='who',
            field=ckeditor.fields.RichTextField(verbose_name='who'),
        ),
        migrations.AlterField(
            model_name='project',
            name='why',
            field=ckeditor.fields.RichTextField(verbose_name='why'),
        ),
    ]
