# Generated by Django 4.0.1 on 2022-04-14 19:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_project_date_alter_project_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='when',
        ),
        migrations.RemoveField(
            model_name='project',
            name='where',
        ),
        migrations.RemoveField(
            model_name='project',
            name='who',
        ),
        migrations.RemoveField(
            model_name='project',
            name='why',
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(max_length=128, verbose_name='slug')),
                ('sub_title', ckeditor.fields.RichTextField(verbose_name='sub_title')),
                ('overview', ckeditor.fields.RichTextField(verbose_name='overview')),
                ('role', models.JSONField(default=list, verbose_name='role')),
                ('duration', models.CharField(max_length=128, verbose_name='duration')),
                ('outcomes', models.JSONField(default=list, verbose_name='outcomes')),
                ('who', ckeditor.fields.RichTextField(verbose_name='who')),
                ('when', ckeditor.fields.RichTextField(verbose_name='when')),
                ('where', ckeditor.fields.RichTextField(verbose_name='where')),
                ('why', ckeditor.fields.RichTextField(verbose_name='why')),
                ('goal', ckeditor.fields.RichTextField(verbose_name='goal')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.project')),
            ],
            options={
                'verbose_name': 'project Translation',
                'db_table': 'main_project_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
