# Generated by Django 4.0.1 on 2022-04-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_introductionparagraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductionparagraphtranslation',
            name='sub_overview',
            field=models.TextField(blank=True),
        ),
    ]
