# Generated by Django 4.0.1 on 2022-04-17 13:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cards_cardstranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttranslation',
            old_name='goal',
            new_name='goal_overview',
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='goal_sub_overview',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='points',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='problem_framing_overview',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
