# Generated by Django 4.0.1 on 2022-04-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_projecttranslation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='image',
            field=models.FileField(upload_to='projects/illustrations'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/illustrations')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
