# Generated by Django 4.0.1 on 2022-04-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_projecttranslation_image_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
