# Generated by Django 4.0.1 on 2022-04-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_projectimage_projectimagetranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimagetranslation',
            old_name='post',
            new_name='project',
        ),
    ]
