# Generated by Django 4.0.1 on 2022-04-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_projectimage_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttranslation',
            name='image',
        ),
    ]
