# Generated by Django 4.0.1 on 2022-04-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_projecttranslation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='image',
            field=models.ImageField(default='', upload_to='projects/illustration'),
            preserve_default=False,
        ),
    ]
