# Generated by Django 4.0.1 on 2022-04-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_introductionparagraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionAboutParagraph',
            fields=[
                ('introductionparagraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.introductionparagraph')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.introductionparagraph',),
        ),
        migrations.CreateModel(
            name='IntroductionExperimentsParagraph',
            fields=[
                ('introductionparagraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.introductionparagraph')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.introductionparagraph',),
        ),
        migrations.CreateModel(
            name='IntroductionLecturesParagraph',
            fields=[
                ('introductionparagraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.introductionparagraph')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.introductionparagraph',),
        ),
        migrations.CreateModel(
            name='IntroductionProjectsParagraph',
            fields=[
                ('introductionparagraph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.introductionparagraph')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.introductionparagraph',),
        ),
    ]
